name: Bug report
description: Create a report to help us improve
title: "[Bug]: "
labels: ["bug", "triage"]
body:
- type: markdown
  attributes:
    value: |
      Before you open a new issue, search through the existing issues to see if others have had the same problem.
- type: textarea
  attributes:
    label: "System Health details"
    description: "Paste the data from the System Health card in Home Assistant (https://www.home-assistant.io//more-info/system-health#github-issues)"
  validations:
    required: true

- type: textarea
  attributes:
    label: "Huawei Solar Setup"
    description: "Describe your setup: which inverter(s) do you have? Do you have an SDongle? Is a power meter type present (single/three phase?)? Do you have a battery (which type?)?. Include the firmware versions if possible."
  validations:
    required: true

- type: dropdown
  id: connection_method
  attributes:
    label: How do you connect to the inverter?
    options:
      - Over serial, with a serial-to-USB stick
      - Over serial, with a serial-to-WiFi stick
      - Via the `SUN2000-<serial_no>` WiFi 
      - Via the SDongle, wireless connection
      - Via the SDongle, wired connection
  validations:
    required: true

- type: textarea
  attributes:
    label: "Describe the issue"
    description: "A clear and concise description of what the issue is."
  validations:
    required: true

- type: markdown
  attributes:
    value: |
      **You MUST include relevant logfiles to debug your issue.**

      For instance: if the integration does not show up in the `+ Add Integration` list, then add any relevant lines you can find in `/config/home-assistant.log` after a full restart of your Home Assistant instance.

      When you don't find any relevant logs, please increase your logging level and try again. To do this, add the following lines to your `/config/configuration.yaml` and restart HA:

      ```yaml
      logger:
        default: debug
        logs:
          custom_components.huawei_solar: debug
          huawei_solar: debug
          pymodbus: debug # only include this if you're having connectivity issues
      ```
      
      Make sure to check for relevant log lines in the **Full logs**, which you can also find in `/config/home-assistant.log`. Do NOT copy&paste info from the summary that you see when going to `System → Logs`, always push the "Load Full Logs" button and look there.

- type: textarea
  attributes:
    label: "Relevant debug logs"
    render: text
  validations:
    required: true
